### PR TITLE
Keep the correct video orientation on transcoding

### LINKED ISSUE #64: Transcoding video doesn't keep the original orientation
Was trying the `Transcode Video` example and it seems that the default Muxer doesn't take in consideration the orientation of the original video, resulting in videos rotated 90° degrees respect to the original. 

Would be best to pass the rotation info to the Muxer. Not sure if orientation can be modified by using a filter in the pipeline, and this will collide with the passed parameter.

### PR DESCRIPTION
**Pull request by daniloercoli**
Fix #64 and upgrade Gradle and Gradle wrapper

### CODE REVIEW

**Comment by smackd40** [comment]
video rotation fix works. How to handle text overlay rotation in relation to video rotation fix?

**Comment by RafagSL** [comment]
@smackd40 +1, this works when just translating, but not when applying a filter.

**Comment by RafagSL** [comment]
Ok, just add 

`int orientation = mediaFileInfo.getRotation();
        mediaComposer.setTargetFile(dstMediaPath, orientation);`

on setTrasncodeParameter method on the ComposerVideoEffectCoreActivity and will keep the orientation.

**Comment by devingDev** [comment]
I am using the  samples and for example when I use Cut Video it will rotate the video by 90 degrees when I use a video I had recorded before. The video was shot in portrait mode and looking at it it shows correctly.
But after using Cut video it is rotated by 90 degrees counter-clockwise.

When I use a landscape recorded video it seems to work though.. very weird.

As this is a sample I assume it uses the class  ComposerTranscodeCoreActivity
which calls this:

`
    protected void setTranscodeParameters(org.m4m.MediaComposer mediaComposer) throws IOException {

        mediaComposer.addSourceFile(mediaUri1);
        int orientation = mediaFileInfo.getRotation();
        mediaComposer.setTargetFile(dstMediaPath, orientation);

....

}
`
so it should be set correctly but it is not.

**Pull request merged**
